<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $udemyProfileUrl = 'https://www.udemy.com/user/dr-muhammad-shakil-ahmad/';

        $courses = [
            [
                'title' => 'Systematic Literature Review : A Practical Guide',
                'slug' => Str::slug('Systematic Literature Review : A Practical Guide'),
                'rating' => 4.4,
                'reviews_count' => 680,
                'duration' => '2 total hours',
                'lectures_count' => 32,
                'level' => 'All Levels',
                'price' => 9.99,
                'category' => 'Literature Review',
                'description' => 'Systematic Literature Review, PRISMA, PICO, PEO, GRADE framework for high ranked journals.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => true,
            ],
            [
                'title' => 'Master Thematic Analysis: A Comprehensive Step-by-Step Guide',
                'slug' => Str::slug('Master Thematic Analysis: A Comprehensive Step-by-Step Guide'),
                'rating' => 4.3,
                'reviews_count' => 51,
                'duration' => '3.5 total hours',
                'lectures_count' => 25,
                'level' => 'All Levels',
                'price' => 9.99,
                'category' => 'Qualitative Research',
                'description' => 'Transform your research skills by learning thematic analysis with Braun & Clarke coding framework.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => true,
            ],
            [
                'title' => 'How to Conduct a Meta-analysis: A Practical Guide',
                'slug' => Str::slug('How to Conduct a Meta-analysis: A Practical Guide'),
                'rating' => 4.1,
                'reviews_count' => 183,
                'duration' => '2.5 total hours',
                'lectures_count' => 34,
                'level' => 'All Levels',
                'price' => 9.99,
                'category' => 'Quantitative Research',
                'description' => '#1 Meta-Analysis Course for Researchers: A Practical guide to effect sizes, forest plots & bias.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => true,
            ],
            [
                'title' => 'The Literature Review : A Comprehensive Six Step Guide',
                'slug' => Str::slug('The Literature Review : A Comprehensive Six Step Guide'),
                'rating' => 4.3,
                'reviews_count' => 78,
                'duration' => '2 total hours',
                'lectures_count' => 28,
                'level' => 'All Levels',
                'price' => 9.99,
                'category' => 'Literature Review',
                'description' => 'The step-by-step process using an applied critical-thinking framework to synthesize literature.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => true,
            ],
            [
                'title' => 'Bibliometric Analysis: A Theoretical Stepwise Guide',
                'slug' => Str::slug('Bibliometric Analysis: A Theoretical Stepwise Guide'),
                'rating' => 4.2,
                'reviews_count' => 138,
                'duration' => '2.5 total hours',
                'lectures_count' => 18,
                'level' => 'All Levels',
                'price' => 9.99,
                'category' => 'Bibliometrics',
                'description' => 'Mastering Bibliometrics; Step-by-Step Guide; Co-Citation networks & VOSviewer science mapping.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => true,
            ],
            [
                'title' => 'How to Conduct Qualitative Research - Researchers Guide',
                'slug' => Str::slug('How to Conduct Qualitative Research - Researchers Guide'),
                'rating' => 4.3,
                'reviews_count' => 75,
                'duration' => '2.5 total hours',
                'lectures_count' => 25,
                'level' => 'Expert',
                'price' => 9.99,
                'category' => 'Qualitative Research',
                'description' => 'Fundamentals of Qualitative Research design, phenomenology, grounded theory & interview coding.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => true,
            ],
            [
                'title' => 'Qualitative Dissertation Proposal: Step-by-Step Guide',
                'slug' => Str::slug('Qualitative Dissertation Proposal: Step-by-Step Guide'),
                'rating' => 4.8,
                'reviews_count' => 43,
                'duration' => '4.5 total hours',
                'lectures_count' => 25,
                'level' => 'All Levels',
                'price' => 9.99,
                'category' => 'Dissertation Help',
                'description' => 'Write a winning dissertation proposal that satisfies defense committees and IRB ethical clearance.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'How to Write a Scientific Paper for High Ranked Journals',
                'slug' => Str::slug('How to Write a Scientific Paper for High Ranked Journals'),
                'rating' => 4.6,
                'reviews_count' => 255,
                'duration' => '2.5 total hours',
                'lectures_count' => 37,
                'level' => 'All Levels',
                'price' => 9.99,
                'category' => 'Journal Publishing',
                'description' => 'Insider secrets from a journal reviewer and editor on structuring papers for top SSCI and Scopus Q1/Q2 journals.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'Dissertation Writing Bootcamp: Defend with Distinction',
                'slug' => Str::slug('Dissertation Writing Bootcamp: Defend with Distinction'),
                'rating' => 4.5,
                'reviews_count' => 29,
                'duration' => '6.5 total hours',
                'lectures_count' => 41,
                'level' => 'All Levels',
                'price' => 9.99,
                'category' => 'Dissertation Help',
                'description' => 'Complete end-to-end guide to writing, revising, formatting, and defending your PhD or Master\'s thesis.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'Advanced NVivo & MAXQDA Qualitative Coding Masterclass',
                'slug' => Str::slug('Advanced NVivo & MAXQDA Qualitative Coding Masterclass'),
                'rating' => 4.7,
                'reviews_count' => 142,
                'duration' => '3 total hours',
                'lectures_count' => 22,
                'level' => 'Intermediate',
                'price' => 9.99,
                'category' => 'Qualitative Research',
                'description' => 'Master node hierarchies, sentiment analysis, cross-tabulation, and visual diagrams in NVivo & MAXQDA.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'Scopus & SSCI Q1 Journal Peer-Review & Revision Strategies',
                'slug' => Str::slug('Scopus & SSCI Q1 Journal Peer-Review & Revision Strategies'),
                'rating' => 4.9,
                'reviews_count' => 188,
                'duration' => '2 total hours',
                'lectures_count' => 19,
                'level' => 'All Levels',
                'price' => 9.99,
                'category' => 'Journal Publishing',
                'description' => 'How to respond to reviewer comments, write response letters, and successfully navigate major revisions.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'Structural Equation Modeling (SEM) with AMOS & SmartPLS 4',
                'slug' => Str::slug('Structural Equation Modeling (SEM) with AMOS & SmartPLS 4'),
                'rating' => 4.6,
                'reviews_count' => 210,
                'duration' => '4 total hours',
                'lectures_count' => 30,
                'level' => 'All Levels',
                'price' => 9.99,
                'category' => 'Quantitative Research',
                'description' => 'Confirmatory Factor Analysis (CFA), path modeling, mediation/moderation analysis, and reporting SEM results.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'Science Mapping & Co-Citation Networks using VOSviewer',
                'slug' => Str::slug('Science Mapping & Co-Citation Networks using VOSviewer'),
                'rating' => 4.5,
                'reviews_count' => 96,
                'duration' => '2 total hours',
                'lectures_count' => 16,
                'level' => 'All Levels',
                'price' => 9.99,
                'category' => 'Bibliometrics',
                'description' => 'Exporting Web of Science and Scopus data to generate cluster maps, keyword co-occurrence, and author networks.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'Academic Grant Writing: Securing HEC & International Funds',
                'slug' => Str::slug('Academic Grant Writing: Securing HEC & International Funds'),
                'rating' => 4.8,
                'reviews_count' => 64,
                'duration' => '3 total hours',
                'lectures_count' => 20,
                'level' => 'All Levels',
                'price' => 9.99,
                'category' => 'Grant Writing',
                'description' => 'Formulating research proposals, project budgets, impact statements, and grant defense strategy.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'Research Methodology & Theoretical Framework Formulation',
                'slug' => Str::slug('Research Methodology & Theoretical Framework Formulation'),
                'rating' => 4.4,
                'reviews_count' => 115,
                'duration' => '2.5 total hours',
                'lectures_count' => 24,
                'level' => 'All Levels',
                'price' => 9.99,
                'category' => 'Research Methods',
                'description' => 'Constructing conceptual models, identifying research gaps, and choosing appropriate philosophical paradigms.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'PRISMA 2020 Protocol & Quality Assessment in SLR',
                'slug' => Str::slug('PRISMA 2020 Protocol & Quality Assessment in SLR'),
                'rating' => 4.6,
                'reviews_count' => 175,
                'duration' => '2 total hours',
                'lectures_count' => 18,
                'level' => 'All Levels',
                'price' => 9.99,
                'category' => 'Literature Review',
                'description' => 'In-depth guide to PRISMA flowcharts, risk of bias assessment tools (NOS, CASP), and protocol registration.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'Executive Academic Mentorship: From Idea to Defense',
                'slug' => Str::slug('Executive Academic Mentorship: From Idea to Defense'),
                'rating' => 4.9,
                'reviews_count' => 82,
                'duration' => '5 total hours',
                'lectures_count' => 35,
                'level' => 'All Levels',
                'price' => 9.99,
                'category' => 'Dissertation Help',
                'description' => 'Strategic guidance for PhD scholars to manage supervisors, stay on track, and pass oral viva defense.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'Applied SPSS Statistical Data Analysis for Beginners & Pros',
                'slug' => Str::slug('Applied SPSS Statistical Data Analysis for Beginners & Pros'),
                'rating' => 4.5,
                'reviews_count' => 310,
                'duration' => '3.5 total hours',
                'lectures_count' => 28,
                'level' => 'All Levels',
                'price' => 9.99,
                'category' => 'Quantitative Research',
                'description' => 'Descriptive stats, ANOVA, multiple regression, reliability testing, and data cleaning step-by-step in SPSS.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
        ];

        foreach ($courses as $c) {
            Course::updateOrCreate(['slug' => $c['slug']], $c);
        }
    }
}
