<?php

namespace Database\Seeders;

use App\Models\Course;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $udemyProfileUrl = 'https://www.udemy.com/user/dr-muhammad-shakil-ahmad/';

        $courses = [
            [
                'title' => 'Systematic Literature Review : A Practical Guide',
                'slug' => Str::slug('Systematic Literature Review : A Practical Guide'),
                'rating' => 4.4,
                'reviews_count' => 680,
                'duration' => '2 total hours',
                'lectures_count' => 32,
                'level' => 'All Levels',
                'price' => 9.99,
                'original_price' => 49.99,
                'image' => 'course_seq_1.png',
                'category' => 'Literature Review',
                'description' => 'Systematic Literature Review, PRISMA, PICO, PEO, GRADE framework for high ranked journals.',
                'udemy_url' => 'https://www.udemy.com/course/systematic-literature-review-a-practical-guide/',
                'is_featured' => true,
            ],
            [
                'title' => 'Master Thematic Analysis: A Comprehensive Step-by-Step Guide',
                'slug' => Str::slug('Master Thematic Analysis: A Comprehensive Step-by-Step Guide'),
                'rating' => 4.3,
                'reviews_count' => 51,
                'duration' => '3.5 total hours',
                'lectures_count' => 25,
                'level' => 'All Levels',
                'price' => 9.99,
                'original_price' => 19.99,
                'image' => 'course_seq_2.png',
                'category' => 'Qualitative Research',
                'description' => 'Transform your research skills by learning thematic analysis with Braun & Clarke coding framework.',
                'udemy_url' => 'https://www.udemy.com/course/master-thematic-analysis-a-comprehensive-step-by-step-guide/',
                'is_featured' => true,
            ],
            [
                'title' => 'The Literature Review : A Comprehensive Six Step Guide',
                'slug' => Str::slug('The Literature Review : A Comprehensive Six Step Guide'),
                'rating' => 4.3,
                'reviews_count' => 78,
                'duration' => '2 total hours',
                'lectures_count' => 28,
                'level' => 'All Levels',
                'price' => 9.99,
                'original_price' => 39.99,
                'image' => 'course_seq_3.png',
                'category' => 'Literature Review',
                'description' => 'The step-by-step process using an applied critical-thinking framework to synthesize literature.',
                'udemy_url' => 'https://www.udemy.com/course/the-literature-review-a-comprehensive-six-step-guide/',
                'is_featured' => true,
            ],
            [
                'title' => 'How to Conduct a Meta-analysis: A Practical Guide',
                'slug' => Str::slug('How to Conduct a Meta-analysis: A Practical Guide'),
                'rating' => 4.0,
                'reviews_count' => 184,
                'duration' => '2.5 total hours',
                'lectures_count' => 34,
                'level' => 'All Levels',
                'price' => 9.99,
                'original_price' => 44.99,
                'image' => 'course_seq_4.png',
                'category' => 'Meta-Analysis',
                'description' => '#1 Meta-Analysis Course for Researchers: A Practical Guide to Meta-Analysis in R & RevMan.',
                'udemy_url' => 'https://www.udemy.com/course/how-to-conduct-a-meta-analysis-a-practical-guide/',
                'is_featured' => true,
            ],
            [
                'title' => 'How to Conduct Qualitative Research - Researchers Guide',
                'slug' => Str::slug('How to Conduct Qualitative Research - Researchers Guide'),
                'rating' => 4.3,
                'reviews_count' => 75,
                'duration' => '2.5 total hours',
                'lectures_count' => 25,
                'level' => 'Expert',
                'price' => 9.99,
                'original_price' => 54.99,
                'image' => 'course_seq_5.png',
                'category' => 'Qualitative Research',
                'description' => 'Fundamentals of Qualitative Research: Methods, Design & Analysis for Academic Papers.',
                'udemy_url' => 'https://www.udemy.com/course/how-to-conduct-qualitative-research-researchers-guide/',
                'is_featured' => true,
            ],
            [
                'title' => 'Qualitative Dissertation Proposal: A Step-by-Step Guide',
                'slug' => Str::slug('Qualitative Dissertation Proposal: A Step-by-Step Guide'),
                'rating' => 4.8,
                'reviews_count' => 43,
                'duration' => '4.5 total hours',
                'lectures_count' => 25,
                'level' => 'All Levels',
                'price' => 9.99,
                'original_price' => 34.99,
                'image' => 'course_seq_6.png',
                'category' => 'Dissertation Help',
                'description' => 'Mastering Qualitative Research: A Practical Guide for Writing Winning Dissertation Proposals.',
                'udemy_url' => 'https://www.udemy.com/course/qualitative-dissertation-proposal-a-step-by-step-guide/',
                'is_featured' => true,
            ],
            [
                'title' => 'How to Write a Scientific Paper for High Ranked Journals',
                'slug' => Str::slug('How to Write a Scientific Paper for High Ranked Journals'),
                'rating' => 4.6,
                'reviews_count' => 255,
                'duration' => '2.5 total hours',
                'lectures_count' => 37,
                'level' => 'All Levels',
                'price' => 9.99,
                'original_price' => 39.99,
                'image' => 'course_seq_7.png',
                'category' => 'Journal Publishing',
                'description' => 'Fundamentals of Writing Research Paper in SSCI, SCI, Scopus Q1/Q2 Journals.',
                'udemy_url' => 'https://www.udemy.com/course/how-to-write-a-scientific-paper-for-high-ranked-journals/',
                'is_featured' => true,
            ],
            [
                'title' => 'Dissertation Writing Bootcamp: Defend with Distinction',
                'slug' => Str::slug('Dissertation Writing Bootcamp: Defend with Distinction'),
                'rating' => 4.5,
                'reviews_count' => 29,
                'duration' => '6.5 total hours',
                'lectures_count' => 41,
                'level' => 'All Levels',
                'price' => 9.99,
                'original_price' => 19.99,
                'image' => 'course_seq_8.png',
                'category' => 'Dissertation Help',
                'description' => 'Master the Art of Dissertation Writing and Presentation.',
                'udemy_url' => 'https://www.udemy.com/course/dissertation-writing-bootcamp-defend-with-distinction/',
                'is_featured' => true,
            ],
            [
                'title' => 'Bibliometric Analysis: A Theoretical Stepwise Guide',
                'slug' => Str::slug('Bibliometric Analysis: A Theoretical Stepwise Guide'),
                'rating' => 4.2,
                'reviews_count' => 138,
                'duration' => '2.5 total hours',
                'lectures_count' => 18,
                'level' => 'All Levels',
                'price' => 9.99,
                'original_price' => 24.99,
                'image' => 'course_seq_9.png',
                'category' => 'Bibliometrics',
                'description' => 'Mastering Bibliometrics; Step-by-Step Guide; Co-Citation analysis; Science Mapping; VOSviewer.',
                'udemy_url' => 'https://www.udemy.com/course/bibliometric-analysis-a-theoretical-stepwise-guide/',
                'is_featured' => true,
            ],
            [
                'title' => 'Publishing in High Ranked Journals: A Beginner\'s Guide',
                'slug' => Str::slug('Publishing in High Ranked Journals: A Beginner\'s Guide'),
                'rating' => 4.1,
                'reviews_count' => 60,
                'duration' => '1.5 total hours',
                'lectures_count' => 27,
                'level' => 'All Levels',
                'price' => 9.99,
                'original_price' => 34.99,
                'image' => 'course_seq_10.png',
                'category' => 'Journal Publishing',
                'description' => 'How to publish in JCR (SSCI, SCI, ISI) High Ranked Impact Factor Journals.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'Statistics for Clinical Research – A practical Guide',
                'slug' => Str::slug('Statistics for Clinical Research – A practical Guide'),
                'rating' => 4.2,
                'reviews_count' => 77,
                'duration' => '2.5 total hours',
                'lectures_count' => 32,
                'level' => 'Expert',
                'price' => 9.99,
                'original_price' => 39.99,
                'image' => 'course_seq_11.png',
                'category' => 'Quantitative Research',
                'description' => 'Sensitivity, Specificity, Hazard Ratio, Life Tables, Clinical Trials & Biostatistics.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'Statistics for Health Professionals - A Practical Guide',
                'slug' => Str::slug('Statistics for Health Professionals - A Practical Guide'),
                'rating' => 4.2,
                'reviews_count' => 25,
                'duration' => '2.5 total hours',
                'lectures_count' => 31,
                'level' => 'All Levels',
                'price' => 9.99,
                'original_price' => 19.99,
                'image' => 'course_seq_12.png',
                'category' => 'Quantitative Research',
                'description' => 'Sensitivity, Specificity, Hazard Ratio, Life Tables, Clinical Trials & Biostatistics.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'How to Find Research Gaps from Literature: A Practicle Guide',
                'slug' => Str::slug('How to Find Research Gaps from Literature: A Practicle Guide'),
                'rating' => 4.4,
                'reviews_count' => 63,
                'duration' => '2 total hours',
                'lectures_count' => 29,
                'level' => 'All Levels',
                'price' => 9.99,
                'original_price' => 34.99,
                'image' => 'course_seq_13.png',
                'category' => 'Literature Review',
                'description' => 'A Comprehensive Guide to Identifying and Developing Research Gaps for Dissertations and Journal Articles.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'Clinical Research Methods and Statistics',
                'slug' => Str::slug('Clinical Research Methods and Statistics'),
                'rating' => 4.4,
                'reviews_count' => 21,
                'duration' => '4 total hours',
                'lectures_count' => 27,
                'level' => 'All Levels',
                'price' => 9.99,
                'original_price' => 19.99,
                'image' => 'course_seq_14.png',
                'category' => 'Research Methods',
                'description' => 'Essential Skills for Conducting and Evaluating Clinical Studies and Medical Research.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'Mastering Advanced Research Methods',
                'slug' => Str::slug('Mastering Advanced Research Methods'),
                'rating' => 4.9,
                'reviews_count' => 18,
                'duration' => '7.5 total hours',
                'lectures_count' => 21,
                'level' => 'All Levels',
                'price' => 9.99,
                'original_price' => 19.99,
                'image' => 'course_seq_15.png',
                'category' => 'Research Methods',
                'description' => 'Advanced Tools and Techniques to Elevate Your Research Design and Analysis.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'Understanding Business Research - A Fundamental Guide',
                'slug' => Str::slug('Understanding Business Research - A Fundamental Guide'),
                'rating' => 4.7,
                'reviews_count' => 10,
                'duration' => '7 total hours',
                'lectures_count' => 37,
                'level' => 'All Levels',
                'price' => 9.99,
                'original_price' => 19.99,
                'image' => 'course_seq_16.png',
                'category' => 'Research Methods',
                'description' => 'Your Comprehensive Guide to Mastering Business Research Methodology & Design.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'Mastering Grant Proposal Writing: A Step-by-Step Guide',
                'slug' => Str::slug('Mastering Grant Proposal Writing: A Step-by-Step Guide'),
                'rating' => 4.4,
                'reviews_count' => 39,
                'duration' => '3 total hours',
                'lectures_count' => 25,
                'level' => 'All Levels',
                'price' => 9.99,
                'original_price' => 29.99,
                'image' => 'course_seq_17.png',
                'category' => 'Grant Writing',
                'description' => 'Unlock Funding Success: Master the Art of Grant Writing & Proposal Formulation.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
            [
                'title' => 'Quantitative Dissertation Proposals: A Step-by-Step Guide',
                'slug' => Str::slug('Quantitative Dissertation Proposals: A Step-by-Step Guide'),
                'rating' => 4.6,
                'reviews_count' => 21,
                'duration' => '6 total hours',
                'lectures_count' => 31,
                'level' => 'All Levels',
                'price' => 9.99,
                'original_price' => 19.99,
                'image' => 'course_seq_18.png',
                'category' => 'Dissertation Help',
                'description' => 'From Concept to Completion: Your Comprehensive Guide to Quantitative Dissertations.',
                'udemy_url' => $udemyProfileUrl,
                'is_featured' => false,
            ],
        ];

        Course::truncate();

        foreach ($courses as $c) {
            Course::create($c);
        }
    }
}
