-- MySQL Export for Research with Shakil
SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE `courses`;
INSERT INTO `courses` (`id`, `title`, `slug`, `rating`, `reviews_count`, `duration`, `lectures_count`, `level`, `price`, `original_price`, `image`, `category`, `description`, `udemy_url`, `is_featured`, `created_at`, `updated_at`) VALUES ('1', 'Systematic Literature Review : A Practical Guide', 'systematic-literature-review-a-practical-guide', '4.4', '680', '2 total hours', '32', 'All Levels', '9.99', '49.99', 'course_seq_1.png', 'Literature Review', 'Systematic Literature Review, PRISMA, PICO, PEO, GRADE framework for high ranked journals.', 'https://www.udemy.com/course/systematic-literature-review-a-practical-guide/', '1', '2026-08-24 16:09:32', '2026-08-24 16:09:32');
INSERT INTO `courses` (`id`, `title`, `slug`, `rating`, `reviews_count`, `duration`, `lectures_count`, `level`, `price`, `original_price`, `image`, `category`, `description`, `udemy_url`, `is_featured`, `created_at`, `updated_at`) VALUES ('2', 'Master Thematic Analysis: A Comprehensive Step-by-Step Guide', 'master-thematic-analysis-a-comprehensive-step-by-step-guide', '4.3', '51', '3.5 total hours', '25', 'All Levels', '9.99', '19.99', 'course_seq_2.png', 'Qualitative Research', 'Transform your research skills by learning thematic analysis with Braun & Clarke coding framework.', 'https://www.udemy.com/course/master-thematic-analysis-a-comprehensive-step-by-step-guide/', '1', '2026-08-24 16:09:32', '2026-08-24 16:09:32');
INSERT INTO `courses` (`id`, `title`, `slug`, `rating`, `reviews_count`, `duration`, `lectures_count`, `level`, `price`, `original_price`, `image`, `category`, `description`, `udemy_url`, `is_featured`, `created_at`, `updated_at`) VALUES ('3', 'The Literature Review : A Comprehensive Six Step Guide', 'the-literature-review-a-comprehensive-six-step-guide', '4.3', '78', '2 total hours', '28', 'All Levels', '9.99', '39.99', 'course_seq_3.png', 'Literature Review', 'The step-by-step process using an applied critical-thinking framework to synthesize literature.', 'https://www.udemy.com/course/the-literature-review-a-comprehensive-six-step-guide/', '1', '2026-08-24 16:09:32', '2026-08-24 16:09:32');
INSERT INTO `courses` (`id`, `title`, `slug`, `rating`, `reviews_count`, `duration`, `lectures_count`, `level`, `price`, `original_price`, `image`, `category`, `description`, `udemy_url`, `is_featured`, `created_at`, `updated_at`) VALUES ('4', 'How to Conduct a Meta-analysis: A Practical Guide', 'how-to-conduct-a-meta-analysis-a-practical-guide', '4', '184', '2.5 total hours', '34', 'All Levels', '9.99', '44.99', 'course_seq_4.png', 'Meta-Analysis', '#1 Meta-Analysis Course for Researchers: A Practical Guide to Meta-Analysis in R & RevMan.', 'https://www.udemy.com/course/how-to-conduct-a-meta-analysis-a-practical-guide/', '1', '2026-08-24 16:09:32', '2026-08-24 16:09:32');
INSERT INTO `courses` (`id`, `title`, `slug`, `rating`, `reviews_count`, `duration`, `lectures_count`, `level`, `price`, `original_price`, `image`, `category`, `description`, `udemy_url`, `is_featured`, `created_at`, `updated_at`) VALUES ('5', 'How to Conduct Qualitative Research - Researchers Guide', 'how-to-conduct-qualitative-research-researchers-guide', '4.3', '75', '2.5 total hours', '25', 'Expert', '9.99', '54.99', 'course_seq_5.png', 'Qualitative Research', 'Fundamentals of Qualitative Research: Methods, Design & Analysis for Academic Papers.', 'https://www.udemy.com/course/how-to-conduct-qualitative-research-researchers-guide/', '1', '2026-08-24 16:09:32', '2026-08-24 16:09:32');
INSERT INTO `courses` (`id`, `title`, `slug`, `rating`, `reviews_count`, `duration`, `lectures_count`, `level`, `price`, `original_price`, `image`, `category`, `description`, `udemy_url`, `is_featured`, `created_at`, `updated_at`) VALUES ('6', 'Qualitative Dissertation Proposal: A Step-by-Step Guide', 'qualitative-dissertation-proposal-a-step-by-step-guide', '4.8', '43', '4.5 total hours', '25', 'All Levels', '9.99', '34.99', 'course_seq_6.png', 'Dissertation Help', 'Mastering Qualitative Research: A Practical Guide for Writing Winning Dissertation Proposals.', 'https://www.udemy.com/course/qualitative-dissertation-proposal-a-step-by-step-guide/', '1', '2026-08-24 16:09:32', '2026-08-24 16:09:32');
INSERT INTO `courses` (`id`, `title`, `slug`, `rating`, `reviews_count`, `duration`, `lectures_count`, `level`, `price`, `original_price`, `image`, `category`, `description`, `udemy_url`, `is_featured`, `created_at`, `updated_at`) VALUES ('7', 'How to Write a Scientific Paper for High Ranked Journals', 'how-to-write-a-scientific-paper-for-high-ranked-journals', '4.6', '255', '2.5 total hours', '37', 'All Levels', '9.99', '39.99', 'course_seq_7.png', 'Journal Publishing', 'Fundamentals of Writing Research Paper in SSCI, SCI, Scopus Q1/Q2 Journals.', 'https://www.udemy.com/course/how-to-write-a-scientific-paper-for-high-ranked-journals/', '1', '2026-08-24 16:09:32', '2026-08-24 16:09:32');
INSERT INTO `courses` (`id`, `title`, `slug`, `rating`, `reviews_count`, `duration`, `lectures_count`, `level`, `price`, `original_price`, `image`, `category`, `description`, `udemy_url`, `is_featured`, `created_at`, `updated_at`) VALUES ('8', 'Dissertation Writing Bootcamp: Defend with Distinction', 'dissertation-writing-bootcamp-defend-with-distinction', '4.5', '29', '6.5 total hours', '41', 'All Levels', '9.99', '19.99', 'course_seq_8.png', 'Dissertation Help', 'Master the Art of Dissertation Writing and Presentation.', 'https://www.udemy.com/course/dissertation-writing-bootcamp-defend-with-distinction/', '1', '2026-08-24 16:09:32', '2026-08-24 16:09:32');
INSERT INTO `courses` (`id`, `title`, `slug`, `rating`, `reviews_count`, `duration`, `lectures_count`, `level`, `price`, `original_price`, `image`, `category`, `description`, `udemy_url`, `is_featured`, `created_at`, `updated_at`) VALUES ('9', 'Bibliometric Analysis: A Theoretical Stepwise Guide', 'bibliometric-analysis-a-theoretical-stepwise-guide', '4.2', '138', '2.5 total hours', '18', 'All Levels', '9.99', '24.99', 'course_seq_9.png', 'Bibliometrics', 'Mastering Bibliometrics; Step-by-Step Guide; Co-Citation analysis; Science Mapping; VOSviewer.', 'https://www.udemy.com/course/bibliometric-analysis-a-theoretical-stepwise-guide/', '1', '2026-08-24 16:09:32', '2026-08-24 16:09:32');
INSERT INTO `courses` (`id`, `title`, `slug`, `rating`, `reviews_count`, `duration`, `lectures_count`, `level`, `price`, `original_price`, `image`, `category`, `description`, `udemy_url`, `is_featured`, `created_at`, `updated_at`) VALUES ('10', 'Publishing in High Ranked Journals: A Beginner\'s Guide', 'publishing-in-high-ranked-journals-a-beginners-guide', '4.1', '60', '1.5 total hours', '27', 'All Levels', '9.99', '34.99', 'course_seq_10.png', 'Journal Publishing', 'How to publish in JCR (SSCI, SCI, ISI) High Ranked Impact Factor Journals.', 'https://www.udemy.com/user/dr-muhammad-shakil-ahmad/', '0', '2026-08-24 16:09:32', '2026-08-24 16:09:32');
INSERT INTO `courses` (`id`, `title`, `slug`, `rating`, `reviews_count`, `duration`, `lectures_count`, `level`, `price`, `original_price`, `image`, `category`, `description`, `udemy_url`, `is_featured`, `created_at`, `updated_at`) VALUES ('11', 'Statistics for Clinical Research – A practical Guide', 'statistics-for-clinical-research-a-practical-guide', '4.2', '77', '2.5 total hours', '32', 'Expert', '9.99', '39.99', 'course_seq_11.png', 'Quantitative Research', 'Sensitivity, Specificity, Hazard Ratio, Life Tables, Clinical Trials & Biostatistics.', 'https://www.udemy.com/user/dr-muhammad-shakil-ahmad/', '0', '2026-08-24 16:09:32', '2026-08-24 16:09:32');
INSERT INTO `courses` (`id`, `title`, `slug`, `rating`, `reviews_count`, `duration`, `lectures_count`, `level`, `price`, `original_price`, `image`, `category`, `description`, `udemy_url`, `is_featured`, `created_at`, `updated_at`) VALUES ('12', 'Statistics for Health Professionals - A Practical Guide', 'statistics-for-health-professionals-a-practical-guide', '4.2', '25', '2.5 total hours', '31', 'All Levels', '9.99', '19.99', 'course_seq_12.png', 'Quantitative Research', 'Sensitivity, Specificity, Hazard Ratio, Life Tables, Clinical Trials & Biostatistics.', 'https://www.udemy.com/user/dr-muhammad-shakil-ahmad/', '0', '2026-08-24 16:09:32', '2026-08-24 16:09:32');
INSERT INTO `courses` (`id`, `title`, `slug`, `rating`, `reviews_count`, `duration`, `lectures_count`, `level`, `price`, `original_price`, `image`, `category`, `description`, `udemy_url`, `is_featured`, `created_at`, `updated_at`) VALUES ('13', 'How to Find Research Gaps from Literature: A Practicle Guide', 'how-to-find-research-gaps-from-literature-a-practicle-guide', '4.4', '63', '2 total hours', '29', 'All Levels', '9.99', '34.99', 'course_seq_13.png', 'Literature Review', 'A Comprehensive Guide to Identifying and Developing Research Gaps for Dissertations and Journal Articles.', 'https://www.udemy.com/user/dr-muhammad-shakil-ahmad/', '0', '2026-08-24 16:09:32', '2026-08-24 16:09:32');
INSERT INTO `courses` (`id`, `title`, `slug`, `rating`, `reviews_count`, `duration`, `lectures_count`, `level`, `price`, `original_price`, `image`, `category`, `description`, `udemy_url`, `is_featured`, `created_at`, `updated_at`) VALUES ('14', 'Clinical Research Methods and Statistics', 'clinical-research-methods-and-statistics', '4.4', '21', '4 total hours', '27', 'All Levels', '9.99', '19.99', 'course_seq_14.png', 'Research Methods', 'Essential Skills for Conducting and Evaluating Clinical Studies and Medical Research.', 'https://www.udemy.com/user/dr-muhammad-shakil-ahmad/', '0', '2026-08-24 16:09:32', '2026-08-24 16:09:32');
INSERT INTO `courses` (`id`, `title`, `slug`, `rating`, `reviews_count`, `duration`, `lectures_count`, `level`, `price`, `original_price`, `image`, `category`, `description`, `udemy_url`, `is_featured`, `created_at`, `updated_at`) VALUES ('15', 'Mastering Advanced Research Methods', 'mastering-advanced-research-methods', '4.9', '18', '7.5 total hours', '21', 'All Levels', '9.99', '19.99', 'course_seq_15.png', 'Research Methods', 'Advanced Tools and Techniques to Elevate Your Research Design and Analysis.', 'https://www.udemy.com/user/dr-muhammad-shakil-ahmad/', '0', '2026-08-24 16:09:32', '2026-08-24 16:09:32');
INSERT INTO `courses` (`id`, `title`, `slug`, `rating`, `reviews_count`, `duration`, `lectures_count`, `level`, `price`, `original_price`, `image`, `category`, `description`, `udemy_url`, `is_featured`, `created_at`, `updated_at`) VALUES ('16', 'Understanding Business Research - A Fundamental Guide', 'understanding-business-research-a-fundamental-guide', '4.7', '10', '7 total hours', '37', 'All Levels', '9.99', '19.99', 'course_seq_16.png', 'Research Methods', 'Your Comprehensive Guide to Mastering Business Research Methodology & Design.', 'https://www.udemy.com/user/dr-muhammad-shakil-ahmad/', '0', '2026-08-24 16:09:32', '2026-08-24 16:09:32');
INSERT INTO `courses` (`id`, `title`, `slug`, `rating`, `reviews_count`, `duration`, `lectures_count`, `level`, `price`, `original_price`, `image`, `category`, `description`, `udemy_url`, `is_featured`, `created_at`, `updated_at`) VALUES ('17', 'Mastering Grant Proposal Writing: A Step-by-Step Guide', 'mastering-grant-proposal-writing-a-step-by-step-guide', '4.4', '39', '3 total hours', '25', 'All Levels', '9.99', '29.99', 'course_seq_17.png', 'Grant Writing', 'Unlock Funding Success: Master the Art of Grant Writing & Proposal Formulation.', 'https://www.udemy.com/user/dr-muhammad-shakil-ahmad/', '0', '2026-08-24 16:09:32', '2026-08-24 16:09:32');
INSERT INTO `courses` (`id`, `title`, `slug`, `rating`, `reviews_count`, `duration`, `lectures_count`, `level`, `price`, `original_price`, `image`, `category`, `description`, `udemy_url`, `is_featured`, `created_at`, `updated_at`) VALUES ('18', 'Quantitative Dissertation Proposals: A Step-by-Step Guide', 'quantitative-dissertation-proposals-a-step-by-step-guide', '4.6', '21', '6 total hours', '31', 'All Levels', '9.99', '19.99', 'course_seq_18.png', 'Dissertation Help', 'From Concept to Completion: Your Comprehensive Guide to Quantitative Dissertations.', 'https://www.udemy.com/user/dr-muhammad-shakil-ahmad/', '0', '2026-08-24 16:09:32', '2026-08-24 16:09:32');

TRUNCATE TABLE `publications`;
INSERT INTO `publications` (`id`, `title`, `authors`, `journal`, `year`, `type`, `abstract`, `url`, `doi`, `is_highlighted`, `created_at`, `updated_at`) VALUES ('1', 'Sustainable Healthcare Management Systems: Economic Vision & Online Readiness', 'Dr. Muhammad Shakil Ahmad (Principal Investigator)', 'Ministry of Higher Education & Scientific Research (Oman Grant)', '2021', 'Grant', 'Research grant awarded to evaluate national digital health infrastructure and economic strategic vision implementation.', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', 'GRANT-OMAN-2021', '1', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `publications` (`id`, `title`, `authors`, `journal`, `year`, `type`, `abstract`, `url`, `doi`, `is_highlighted`, `created_at`, `updated_at`) VALUES ('2', 'Higher Education Quality & Digital Transformation Assessment', 'Dr. Muhammad Shakil Ahmad (Lead Researcher)', 'Higher Education Commission (HEC), Pakistan Grant', '2020', 'Grant', 'Nationwide grant project assessing institutional readiness and faculty development for online higher education delivery.', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', 'GRANT-HEC-2020', '1', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `publications` (`id`, `title`, `authors`, `journal`, `year`, `type`, `abstract`, `url`, `doi`, `is_highlighted`, `created_at`, `updated_at`) VALUES ('3', 'Green Employee Empowerment: A Systematic Literature Review on State-of-art in Green Human Resource Management', 'Tariq, S., Jan, F. A., Ahmad, M. S.', 'Quality & Quantity: International Journal of Methodology, 50(1), 237-269', '2016', 'Systematic Review', 'Systematic literature review synthesizing state-of-the-art developments in green human resource management and employee empowerment.', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', '10.1007/s11135-014-0146-0', '1', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `publications` (`id`, `title`, `authors`, `journal`, `year`, `type`, `abstract`, `url`, `doi`, `is_highlighted`, `created_at`, `updated_at`) VALUES ('4', 'Parenting styles and aggression among young adolescents: a systematic review of literature', 'Ahmad, M. S.', 'Community Mental Health Journal', '2019', 'Systematic Review', 'Systematic synthesis investigating associations between parenting paradigms and adolescent behavioral aggression.', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', '10.1007/s10597-019-00412-x', '1', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `publications` (`id`, `title`, `authors`, `journal`, `year`, `type`, `abstract`, `url`, `doi`, `is_highlighted`, `created_at`, `updated_at`) VALUES ('5', 'Parenting styles and academic achievement of young adolescents: A systematic literature review', 'Ahmad, M. S.', 'Quality and Quantity: International Journal of Methodology', '2015', 'Systematic Review', 'Comprehensive literature review mapping parenting dimensions to adolescent educational achievement.', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', '10.1007/s11135-014-0062-3', '1', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `publications` (`id`, `title`, `authors`, `journal`, `year`, `type`, `abstract`, `url`, `doi`, `is_highlighted`, `created_at`, `updated_at`) VALUES ('6', 'Using food choice motives to model Pakistani ethnic food purchase intention among tourists', 'Ahmad, M. S., et al.', 'British Food Journal, 22(6), 1731-1753', '2020', 'Journal Article', 'Modeling tourist purchase intentions for ethnic cuisine based on multidimensional food choice motives.', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', '10.1108/BFJ-08-2019-0604', '0', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `publications` (`id`, `title`, `authors`, `journal`, `year`, `type`, `abstract`, `url`, `doi`, `is_highlighted`, `created_at`, `updated_at`) VALUES ('7', 'Performance Appraisal Satisfaction and Turnover Intention: The Mediating Role of Work Engagement', 'Memon, M., Ting, H., & Ahmad, M. S.', 'Management Decision, 58(6), 1053-1066', '2020', 'Journal Article', 'Empirical study on appraisal satisfaction, employee retention, and mediation of work engagement.', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', '10.1108/MD-06-2018-0685', '0', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `publications` (`id`, `title`, `authors`, `journal`, `year`, `type`, `abstract`, `url`, `doi`, `is_highlighted`, `created_at`, `updated_at`) VALUES ('8', 'Health Practitioners interaction with Pharmaceutical Sales Representatives: Impact on Prescription Behaviour', 'Faisal, A., & Ahmad, M. S.', 'Community Mental Health Journal, 56, 456–463', '2019', 'Journal Article', 'Evaluating pharmaceutical marketing interactions and medical practitioner prescription behaviors.', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', '10.1007/s10597-019-00489-3', '0', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `publications` (`id`, `title`, `authors`, `journal`, `year`, `type`, `abstract`, `url`, `doi`, `is_highlighted`, `created_at`, `updated_at`) VALUES ('9', 'Factors that Influence County Government Expenditures and Revenues: A Study of Florida County Governments', 'Cho, K. W., Brower, R., & Ahmad, M. S.', 'Lex localis - Journal of Local Self-Government, 16(1), 47-76', '2018', 'Journal Article', 'Fiscal determinants and governance factors shaping county government revenue and expenditure patterns in Florida.', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', '10.4335/16.1.47-76(2018)', '0', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `publications` (`id`, `title`, `authors`, `journal`, `year`, `type`, `abstract`, `url`, `doi`, `is_highlighted`, `created_at`, `updated_at`) VALUES ('10', 'Factors Affecting Purchase Intention and Social Media Publicity of Green Products: The Mediating Role of Concern for Consequences', 'Zahid, M. M., Ali, B., Ahmad, M. S., & Ramayah, T.', 'Corporate Social Responsibility & Environmental Management, 25(3), 225-236', '2018', 'Journal Article', 'Structural model assessing green product purchase intentions and social media publicity drivers.', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', '10.1002/csr.1450', '0', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `publications` (`id`, `title`, `authors`, `journal`, `year`, `type`, `abstract`, `url`, `doi`, `is_highlighted`, `created_at`, `updated_at`) VALUES ('11', 'Barriers to empowerment: Assessment of community-led local development organizations in Pakistan', 'Ahmad, M. S., & Abu Talib, N.', 'Renewable and Sustainable Energy Reviews, 74, 1361–1370', '2017', 'Journal Article', 'Assessment of community-led local development frameworks, organizational capacity, and empowerment constraints.', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', '10.1016/j.rser.2016.11.161', '1', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `publications` (`id`, `title`, `authors`, `journal`, `year`, `type`, `abstract`, `url`, `doi`, `is_highlighted`, `created_at`, `updated_at`) VALUES ('12', 'Impact of Islamic Work Ethics on organizational Citizenship Behavior among Female Academic Staff: The mediating role of employee engagement', 'Uzma, T., & Ahmad, M. S.', 'Applied Research in Quality of Life, 12(3), 693-717', '2017', 'Journal Article', 'Investigating work ethics, employee engagement, and citizenship behavior among female university faculty.', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', '10.1007/s11482-016-9484-4', '0', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `publications` (`id`, `title`, `authors`, `journal`, `year`, `type`, `abstract`, `url`, `doi`, `is_highlighted`, `created_at`, `updated_at`) VALUES ('13', 'Student Well-Being in Chinese Adolescents in Hong Kong: Theory, Intervention and Research', 'Wahab, A., & Ahmad, M. S.', 'Applied Research in Quality of Life, 12(3), 761-763', '2017', 'Journal Article', 'Critical review of adolescent well-being interventions, theoretical frameworks, and educational policy.', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', '10.1007/s11482-016-9488-0', '0', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `publications` (`id`, `title`, `authors`, `journal`, `year`, `type`, `abstract`, `url`, `doi`, `is_highlighted`, `created_at`, `updated_at`) VALUES ('14', 'Forecasting the consumption of gasoline in transport sector in Pakistan based on ARIMA model', 'Bhutto, A. W., & Ahmad, M. S.', 'Environmental Progress & Sustainable Energy, 36(5), 1490–1497', '2017', 'Journal Article', 'Time-series ARIMA econometric modeling for gasoline consumption forecasting in national transportation.', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', '10.1002/ep.12586', '0', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `publications` (`id`, `title`, `authors`, `journal`, `year`, `type`, `abstract`, `url`, `doi`, `is_highlighted`, `created_at`, `updated_at`) VALUES ('15', 'Exploring Resources, Life-balance and Wellbeing of Women who work in a Global Context', 'Khalid, S., Ahmad, M. S., Jadoon, I. K., Bilal, S., & Farooq, N.', 'Applied Research in Quality of Life, 12(4), 1029-1031', '2017', 'Journal Article', 'Qualitative examination of resource allocation, work-life balance, and well-being among women in global careers.', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', '10.1007/s11482-016-9498-y', '0', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `publications` (`id`, `title`, `authors`, `journal`, `year`, `type`, `abstract`, `url`, `doi`, `is_highlighted`, `created_at`, `updated_at`) VALUES ('16', 'Analysis of community empowerment on projects sustainability: Moderating role of sense of community', 'Ahmad, M. S., & Abu Talib, N.', 'Social Indicators Research, 129(3), 1039-1056', '2016', 'Journal Article', 'Evaluating community empowerment dimensions and project longevity with moderating effects of social cohesion.', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', '10.1007/s11205-015-1161-0', '1', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `publications` (`id`, `title`, `authors`, `journal`, `year`, `type`, `abstract`, `url`, `doi`, `is_highlighted`, `created_at`, `updated_at`) VALUES ('17', 'Effect of Multidimensional Top Management Support on Project Success: An Empirical investigation', 'Ahmad, R., Azmi, N., & Ahmad, M. S.', 'Quality and Quantity: International Journal of Methodology, 50(1), 151-176', '2016', 'Journal Article', 'Empirical testing of top management support dimensions on project completion metrics and stakeholder satisfaction.', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', '10.1007/s11135-014-0142-4', '0', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `publications` (`id`, `title`, `authors`, `journal`, `year`, `type`, `abstract`, `url`, `doi`, `is_highlighted`, `created_at`, `updated_at`) VALUES ('18', 'Relationship between parenting styles and academic performance of adolescents: mediating role of self-efficacy', 'Masud, H., Ahmad, M. S., Jan, F. A., & Jamil, A.', 'Asia Pacific Education Review, 17(1), 121-131', '2016', 'Journal Article', 'Structural mediation model testing parenting styles, academic self-efficacy, and student GPA outcomes.', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', '10.1007/s12564-015-9413-6', '0', '2026-08-24 13:49:02', '2026-08-24 13:49:02');

TRUNCATE TABLE `services`;
INSERT INTO `services` (`id`, `title`, `slug`, `icon`, `short_description`, `full_description`, `features`, `target_audience`, `is_active`, `sort_order`, `created_at`, `updated_at`) VALUES ('1', 'Dissertation & Thesis Coaching', 'dissertation-thesis-coaching', 'fas fa-graduation-cap', '1-on-1 personalized guidance for thesis proposal drafting, research methodology design, and defense preparation.', 'Comprehensive mentorship tailored for Master\'s and PhD candidates. Detailed guidance is provided for literature gap identification, research question formulation, methodology selection, data collection strategy, and defense slide deck optimization.', '[\"Proposal Structuring & Review\",\"Theoretical Framework Alignment\",\"Defense Mock Sessions & Q&A Prep\",\"IRB \\/ Ethics Committee Guidance\"]', 'PhD Candidates & Master\'s Researchers', '1', '1', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `services` (`id`, `title`, `slug`, `icon`, `short_description`, `full_description`, `features`, `target_audience`, `is_active`, `sort_order`, `created_at`, `updated_at`) VALUES ('2', 'Systematic Literature Review & Meta-Analysis Consulting', 'systematic-literature-review-meta-analysis-consulting', 'fas fa-book-open', 'End-to-end guidance on PRISMA guidelines, protocol registration, search matrix, data extraction & meta-analytic modeling.', 'Transform scattered literature into high-impact systematic reviews. Structured advisory covers PRISMA 2020 compliance, database search strings (Scopus, Web of Science, PubMed), quality appraisal tools, and effect size synthesis.', '[\"PRISMA 2020 Compliant Protocol\",\"Search String & Database Strategy\",\"Risk of Bias & Quality Appraisal\",\"Bibliometric & Meta-Analysis Setup\"]', 'Academic Researchers & Faculty', '1', '2', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `services` (`id`, `title`, `slug`, `icon`, `short_description`, `full_description`, `features`, `target_audience`, `is_active`, `sort_order`, `created_at`, `updated_at`) VALUES ('3', 'Scientific Paper Writing & Journal Submission Support', 'scientific-paper-writing-journal-submission-support', 'fas fa-feather-alt', 'Expert editing, journal targeting, response to reviewers, and structural polishing for Scopus & WOS indexed journals.', 'Maximize your publication success rate in top-tier journals (SSCI, SCI, Scopus Q1/Q2). Receive detailed review of your manuscript structure, Academic English flow, reviewer response letter drafting, and journal matching.', '[\"Journal Selection & Impact Matching\",\"Pre-submission Peer Review\",\"Response to Reviewers Drafting\",\"Academic English & Style Refinement\"]', 'Early & Mid-career Researchers', '1', '3', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `services` (`id`, `title`, `slug`, `icon`, `short_description`, `full_description`, `features`, `target_audience`, `is_active`, `sort_order`, `created_at`, `updated_at`) VALUES ('4', 'Grant Writing & Research Advisory', 'grant-writing-research-advisory', 'fas fa-award', 'Consultancy for national and international research grant applications (HEC, Ministry grants, international funds).', 'Securing competitive research funding requires a compelling narrative, realistic budget breakdown, clear milestone matrix, and demonstrated societal impact. Leverage Dr. Shakil\'s track record in securing grants from Oman MoHESR and HEC Pakistan.', '[\"Grant Proposal Concept Notes\",\"Budget & Milestones Planning\",\"Societal & Economic Impact Framing\",\"ORIC \\/ Institutional Alignment\"]', 'Universities & Institutional PIs', '1', '4', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `services` (`id`, `title`, `slug`, `icon`, `short_description`, `full_description`, `features`, `target_audience`, `is_active`, `sort_order`, `created_at`, `updated_at`) VALUES ('5', '1-on-1 Academic & Career Life Coaching', '1-on-1-academic-career-life-coaching', 'fas fa-user-tie', 'Personalized executive coaching to overcome academic burnout, establish career direction, and build academic brand.', 'Tailored coaching sessions focusing on productivity systems, research career roadmap, managing academic stress, building ORCID / Google Scholar visibility, and achieving work-life balance in higher education.', '[\"Academic Career Roadmap\",\"Burnout & Productivity Coaching\",\"Personal Academic Branding\",\"Time Management & Focus Frameworks\"]', 'Academicians & Corporate Executives', '1', '5', '2026-08-24 13:49:02', '2026-08-24 13:49:02');

TRUNCATE TABLE `testimonials`;
INSERT INTO `testimonials` (`id`, `name`, `role_or_course`, `feedback`, `rating`, `avatar_initials`, `is_featured`, `created_at`, `updated_at`) VALUES ('1', 'Andrew', 'PhD Candidate', 'This course was the key to my successful defense.', '5', 'A', '1', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `testimonials` (`id`, `name`, `role_or_course`, `feedback`, `rating`, `avatar_initials`, `is_featured`, `created_at`, `updated_at`) VALUES ('2', 'Michael', 'Master\'s Researcher', 'Transformed my research into a strong defense.', '5', 'M', '1', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `testimonials` (`id`, `name`, `role_or_course`, `feedback`, `rating`, `avatar_initials`, `is_featured`, `created_at`, `updated_at`) VALUES ('3', 'Erich', 'DBA Scholar', 'Turned my ideas into a polished dissertation.', '5', 'E', '1', '2026-08-24 13:49:02', '2026-08-24 13:49:02');
INSERT INTO `testimonials` (`id`, `name`, `role_or_course`, `feedback`, `rating`, `avatar_initials`, `is_featured`, `created_at`, `updated_at`) VALUES ('4', 'Sarah', 'University Faculty', 'Clear, practical, and highly methodical step-by-step guidance.', '5', 'S', '1', '2026-08-24 13:49:02', '2026-08-24 13:49:02');

TRUNCATE TABLE `site_settings`;
INSERT INTO `site_settings` (`key`, `value`, `group`, `type`, `created_at`, `updated_at`) VALUES
('site_title', 'Dr. Muhammad Shakil Ahmad', 'general', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('hero_name', 'Dr. Muhammad Shakil Ahmad', 'hero', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('hero_headline', 'Master High-Impact Research & Academic Publishing', 'hero', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('hero_subtitle', 'Senior Lecturer at Teesside University (UK) & Management Researcher', 'hero', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('hero_tagline', 'Structured step-by-step masterclasses, 1-on-1 dissertation coaching, and quantitative/qualitative methodologies for global researchers.', 'hero', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('home_hero_bg_image', 'images/junaid_zaida_library_bg.jpg', 'home', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('hero_portrait_image', 'images/dr_shakil_hero.jpg', 'hero', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('home_bio_image', 'images/dr_shakil_presentation_quote.jpg', 'home', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('home_quote_image', 'images/dr_shakil_impact_factor_presentation.jpg', 'home', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('stat_learners', '16,000+', 'stats', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('stat_reviews', '1,800+', 'stats', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('stat_workshops', '50+', 'stats', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('stat_scholars_trained', '12,000+', 'stats', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('stat_h_index', '39', 'stats', 'number', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('stat_ssci_papers', '90+', 'stats', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('contact_email', 'info@researchwithshakil.com', 'contact', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('whatsapp_number', '+92 300 0000000', 'contact', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('google_scholar_url', 'https://scholar.google.com/citations?user=Kr6MOa0AAAAJ&hl=en&oi=ao', 'social', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('udemy_profile_url', 'https://www.udemy.com/user/dr-muhammad-shakil-ahmad/', 'social', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('linkedin_url', 'https://linkedin.com', 'social', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('twitter_url', 'https://twitter.com', 'social', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('footer_about_text', 'Research Methodology & Academic Advisory', 'footer', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('footer_copyright', 'Research with Shakil | All rights reserved', 'footer', 'string', '2026-08-24 13:49:02', '2026-08-24 13:49:02');

TRUNCATE TABLE `awards`;
INSERT INTO `awards` (`id`, `title`, `organization`, `year`, `description`, `sort_order`, `created_at`, `updated_at`) VALUES
('1', 'Young Scholar Award (2015)', 'American Society of Public Administration (ASPA)', '2015', 'Honored for outstanding contributions to public administration research and sustainable management frameworks.', '1', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('2', 'Member - American Society of Public Administration', 'ASPA International Council', 'Active Member', 'Contributing to global dialogues on public sector dignity and organizational governance.', '2', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('3', 'Community of Inquiry Framework Member', 'University of Calgary', 'Active Member', 'Collaborating on digital pedagogy, online readiness, and cognitive presence in higher education.', '3', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('4', 'Associate Regional Director', 'International Institute of Marketing Professionals (IIMP, Canada)', 'Regional Director', 'Leading regional marketing education standards and professional development programs.', '4', '2026-08-24 13:49:02', '2026-08-24 13:49:02');

TRUNCATE TABLE `qualifications`;
INSERT INTO `qualifications` (`id`, `label`, `title`, `institution`, `icon`, `icon_color`, `sort_order`, `created_at`, `updated_at`) VALUES
('1', 'Degree', 'PhD in Management', 'Management & Governance Research', 'fa-graduation-cap', '#1e3a8a', '1', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('2', 'Academic Role', 'Senior Lecturer & Researcher', '15+ Years Academic Leadership', 'fa-chalkboard-teacher', '#0284c7', '2', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('3', 'Google Scholar', 'H-Index 39', '1,800+ Citations', 'fa-award', '#eab308', '3', '2026-08-24 13:49:02', '2026-08-24 13:49:02'),
('4', 'Publications', '90+ Research Papers', 'Scopus Q1 & SSCI Peer-Reviewed', 'fa-book', '#166534', '4', '2026-08-24 13:49:02', '2026-08-24 13:49:02');

SET FOREIGN_KEY_CHECKS=1;
